name: CI

on: [push]
jobs:
  job:
    name: ${{ matrix.os }}-cmake-build
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest]
    steps:
      - uses: actions/checkout@v6.0.2
      - name: install alsa pulse and jack
        run: sudo apt-get -y install libasound2-dev libpulse-dev libjack-dev cmake
        if: "contains( matrix.os, 'ubuntu')"
      - name: configure
        run: |
          cmake -H. -Bbuild -DCMAKE_BUILD_TYPE=Release
        if: "!contains( matrix.os, 'windows')"
      - name: building and testing
        run: |
          cmake --build build --config Release -j4
        if: "!contains( matrix.os, 'windows')"
